services:
  mysql:
    image: mysql:8.0
    container_name: bookstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hallo123!
      MYSQL_DATABASE: bookStore
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      interval: 10s

  bookstore-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookstore-network
    restart: on-failure

volumes:
  mysql-data:

networks:
  bookstore-network:
    driver: bridge